# Generated by Django 4.2.16 on 2024-10-17 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="jobs.jobtemplate",
            ),
        ),
    ]
