# Generated by Django 4.2.16 on 2024-10-17 23:13

from django.db import migrations, models


def assign_unique_archive_ids(apps, schema_editor):
    ArchivedJob = apps.get_model('jobs', 'ArchivedJob')
    for index, job in enumerate(ArchivedJob.objects.all().order_by('id'), start=1):
        job.archive_id = index
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_template"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archivedjob",
            options={"ordering": ["archive_id"]},
        ),
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="archivedjob",
            name="archive_id",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(assign_unique_archive_ids),
        migrations.AlterField(
            model_name="archivedjob",
            name="archive_id",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="job",
            name="archive_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="archivedjob",
            name="original_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
