# Generated by Django 4.2.16 on 2024-10-17 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_archivedjob_options_alter_job_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={},
        ),
    ]
