# Generated by Django 4.2.16 on 2024-10-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wod20th", "0031_actiontemplate_asset_shapeshifterform_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="target_asset",
        ),
        migrations.RemoveField(
            model_name="action",
            name="template",
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="account",
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="character",
        ),
        migrations.RemoveField(
            model_name="charactersheet",
            name="db_object",
        ),
        migrations.AlterUniqueTogether(
            name="note",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="note",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="note",
            name="character",
        ),
        migrations.DeleteModel(
            name="ShapeshifterForm",
        ),
        migrations.DeleteModel(
            name="Stat",
        ),
        migrations.DeleteModel(
            name="Action",
        ),
        migrations.DeleteModel(
            name="ActionTemplate",
        ),
        migrations.DeleteModel(
            name="Asset",
        ),
        migrations.DeleteModel(
            name="CharacterSheet",
        ),
        migrations.DeleteModel(
            name="Note",
        ),
    ]
