# Generated by Django 4.2.16 on 2024-10-17 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("requests", "0002_archivedrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="additional_players",
            field=models.ManyToManyField(
                blank=True,
                related_name="accessible_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
